from __future__ import annotations

import subprocess
from pathlib import Path

from llm_sca_tooling.indexing.service import IndexingService
from llm_sca_tooling.plugins.omniorb_idl.idl_parser import parse_idl
from llm_sca_tooling.schemas.enums import GraphEdgeType, GraphNodeType
from llm_sca_tooling.storage import initialize_workspace


def test_idl_parser_extracts_interface_methods() -> None:
    parsed = parse_idl("interface Calculator { long add(in long a, in long b); };")
    assert parsed[0]["name"] == "Calculator"
    assert parsed[0]["methods"][0]["name"] == "add"


def test_omniorb_plugin_emits_idl_edges_and_generated_nodes(tmp_path: Path) -> None:
    root = tmp_path / "idl_repo"
    root.mkdir()
    (root / "calculator.idl").write_text(
        "interface Calculator { long add(in long a, in long b); };\n", encoding="utf-8"
    )
    (root / "calculator_servant.cc").write_text(
        "class Calculator_i : public POA_Calculator { long add(long a, long b); };\n",
        encoding="utf-8",
    )
    (root / "calculator_idl.py").write_text(
        "# generated by omniidl\nclass Calculator: pass\n", encoding="utf-8"
    )
    (root / "client.py").write_text(
        "import calculator_idl\n\ndef run(calc):\n    return calc.add(1, 2)\n",
        encoding="utf-8",
    )
    subprocess.run(["git", "init"], cwd=root, check=True, stdout=subprocess.DEVNULL)
    subprocess.run(["git", "add", "."], cwd=root, check=True)
    subprocess.run(
        [
            "git",
            "-c",
            "user.email=test@example.com",
            "-c",
            "user.name=Test",
            "commit",
            "-m",
            "init",
        ],
        cwd=root,
        check=True,
        stdout=subprocess.DEVNULL,
    )
    workspace = initialize_workspace(tmp_path / "workspace")
    try:
        result = IndexingService(workspace).graph_build(root)
        assert workspace.graph.fetch_nodes_by_type(
            result.repo_id, GraphNodeType.IDL_INTERFACE
        )
        assert workspace.graph.fetch_edges_by_type(
            result.repo_id, GraphEdgeType.IMPLEMENTS
        )
        assert workspace.graph.fetch_edges_by_type(
            result.repo_id, GraphEdgeType.CONSUMES
        )
        assert workspace.graph.fetch_edges_by_type(result.repo_id, GraphEdgeType.FFI)
    finally:
        workspace.close()
