"""Change-type classification from changed symbol lists."""

from __future__ import annotations

import re

from llm_sca_tooling.blast_radius.models import ChangeType

_IDL_PATTERNS = re.compile(
    r"\.(proto|thrift|avro|openapi|swagger|idl|capnp|fbs)$", re.IGNORECASE
)
_GENERATED_MARKERS = re.compile(
    r"(generated|autogenerated|auto_generated|_pb2|_grpc|\.gen\.)", re.IGNORECASE
)
_SECURITY_KEYWORDS = re.compile(
    r"\b(auth|crypt|secret|credential|password|token|permission|cwe|inject|sql)\b",
    re.IGNORECASE,
)


def classify_change_type(
    changed_symbol_ids: list[str],
    *,
    changed_file_paths: list[str] | None = None,
    is_public_api: bool = False,
    has_security_context: bool = False,
) -> tuple[ChangeType, list[ChangeType]]:
    """Return primary change type and applicable types."""
    file_paths = changed_file_paths or []
    applicable: list[ChangeType] = []

    # Generated file check
    if any(_GENERATED_MARKERS.search(p) for p in file_paths):
        applicable.append(ChangeType.generated_file_change)

    # IDL/schema check
    if any(_IDL_PATTERNS.search(p) for p in file_paths):
        applicable.append(ChangeType.idl_schema_contract_change)

    # Public API check — only via explicit flag or exported-symbol naming conventions
    if is_public_api:
        applicable.append(ChangeType.public_api_change)

    # Security check — file paths and explicit flag only (not symbol IDs)
    if has_security_context or any(_SECURITY_KEYWORDS.search(p) for p in file_paths):
        applicable.append(ChangeType.security_sensitive_change)

    if not applicable:
        return ChangeType.internal_implementation, [ChangeType.internal_implementation]
    if len(applicable) > 1:
        return ChangeType.mixed, applicable
    return applicable[0], applicable


def _is_internal(symbol_id: str) -> bool:
    name = symbol_id.split(":")[-1]
    return name.startswith("_")
