"""Generated-stub impact reporting."""

from __future__ import annotations

import re

from llm_sca_tooling.blast_radius.models import GeneratedStubImpactNote

_GENERATED_RE = re.compile(
    r"(generated|autogenerated|_pb2|_grpc|\.gen\.)", re.IGNORECASE
)


def detect_generated_stub_notes(
    diff_id: str,
    changed_file_paths: list[str],
    *,
    manual_edit_allowed: bool = False,
) -> list[GeneratedStubImpactNote]:
    notes: list[GeneratedStubImpactNote] = []
    for path in changed_file_paths:
        if _GENERATED_RE.search(path):
            notes.append(
                GeneratedStubImpactNote(
                    diff_id=diff_id,
                    generated_file_path=path,
                    generator_source="unknown",
                    source_contract_node_id=f"contract:{path}",
                    impact_type="generated_file_directly_changed",
                    manual_edit_policy_flag=not manual_edit_allowed,
                    recommended_action=(
                        "Regenerate from source contract and do not edit manually."
                        if not manual_edit_allowed
                        else "Manual edit permitted by allowlist."
                    ),
                )
            )
    return notes
