"""Phase 7 interface plugin system tests."""

from __future__ import annotations

import asyncio
from pathlib import Path
from urllib.parse import quote

import pytest

from llm_sca_tooling.indexing.service import IndexingService
from llm_sca_tooling.mcp_server import MCPServer, McpServerConfig
from llm_sca_tooling.plugins.backlog import backlog_plugins
from llm_sca_tooling.plugins.base import PluginConfig, repo_files
from llm_sca_tooling.plugins.http_rest import match_paths, normalize_url_path
from llm_sca_tooling.plugins.http_rest.openapi_parser import parse_openapi_file
from llm_sca_tooling.plugins.interface_record import (
    GeneratedArtifactRecord,
    InterfaceKind,
    InterfaceOperation,
    InterfaceRecord,
    OperationParameter,
    OperationType,
    make_interface_id,
    make_operation_id,
)
from llm_sca_tooling.plugins.omniorb_idl.plugin import OmniOrbIdlPlugin
from llm_sca_tooling.plugins.registry import (
    Plugin,
    PluginRegistry,
    build_default_registry,
)
from llm_sca_tooling.plugins.service import reload_plugins
from llm_sca_tooling.plugins.store import InterfaceRecordStore
from llm_sca_tooling.plugins.traversal import CrossLanguageTraverser
from llm_sca_tooling.plugins.websocket.plugin import WebSocketPlugin
from llm_sca_tooling.schemas.graph import GraphEdgeType
from llm_sca_tooling.storage import WorkspaceStore


def _write_http_repo(root: Path) -> None:
    (root / "server.py").write_text("""
from fastapi import FastAPI
app = FastAPI()

@app.get("/users/{id}")
def get_user(id: int):
    return {"id": id}
""")
    (root / "client.ts").write_text("""
export async function loadUser() {
  return fetch("/users/{id}");
}
""")
    (root / "openapi.yaml").write_text("""
openapi: "3.0.0"
paths:
  /orders/{id}:
    get:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: ok
""")


def _write_websocket_repo(root: Path) -> None:
    (root / "socket_server.py").write_text("""
import socketio
sio = socketio.Server()

@sio.on("chat:message")
def on_message(data):
    return data
""")
    (root / "socket_client.ts").write_text("""
const socket = io("/chat");
socket.emit("chat:message", { text: "hi" });
""")


def _write_idl_repo(root: Path) -> None:
    (root / "calculator.idl").write_text("""
interface Calculator {
  long add(in long left, in long right);
};
""")
    (root / "calculatorSK.cc").write_text("// generated by omniidl\n")
    (root / "calculator_idl.py").write_text("# generated by omniidl\n")


def test_interface_record_models_round_trip() -> None:
    interface_id = make_interface_id("http-rest", InterfaceKind.http, "GET /x", "repo")
    operation = InterfaceOperation(
        operation_id=make_operation_id(interface_id, "/x", "GET"),
        interface_id=interface_id,
        name="/x",
        operation_type=OperationType.route,
        parameters=[
            OperationParameter(
                name="id",
                location="path",
                schema={"type": "string"},
                required=True,
            )
        ],
    )
    record = InterfaceRecord(
        interface_id=interface_id,
        kind=InterfaceKind.http,
        plugin_id="http-rest",
        plugin_version="0.1.0",
        interface_name="GET /x",
        operations=[operation],
        generated_artifacts=[
            GeneratedArtifactRecord(
                artifact_id="art:1",
                source_interface_id=interface_id,
                generator_tool="openapi-generator",
            )
        ],
    )
    assert InterfaceRecord.model_validate_json(record.model_dump_json()).interface_id
    assert operation.parameters[0].schema_ == {"type": "string"}


async def test_registry_capability_availability_and_backlog() -> None:
    registry = PluginRegistry()
    registry.register(Plugin(plugin_id="custom", name="Custom", version="1.0"))
    with pytest.raises(ValueError):
        registry.register(Plugin(plugin_id="custom", name="Dup", version="1.0"))
    assert registry.get("custom") is not None
    assert registry.capability_report()
    assert [p.plugin_id for p in await registry.available_plugins()] == ["custom"]
    registry.unregister("custom")
    assert registry.get("custom") is None

    for plugin in backlog_plugins():
        avail = await plugin.check_availability()
        assert avail.plugin_id == plugin.plugin_id
        cap = plugin.describe_capability()
        assert cap.interface_kinds
        # Real plugins detect from empty repo gracefully (return empty list)
        records = await plugin.detect(None, None, [])  # type: ignore[arg-type]
        assert isinstance(records, list)


def test_url_normalizer_and_openapi_parser(tmp_path: Path) -> None:
    _write_http_repo(tmp_path)
    assert normalize_url_path("HTTPS://EXAMPLE.test/users//<int:id>/?q=1") == (
        "/users/{id}"
    )
    assert normalize_url_path("/users/:id") == "/users/{id}"
    assert match_paths("/users/{id}", "/users/{user_id}") == "analyser"
    records = parse_openapi_file(
        tmp_path / "openapi.yaml", repo_id="repo:test", snapshot_id="snap:test"
    )
    assert records[0].interface_name == "GET /orders/{id}"
    assert records[0].operations[0].parameters[0].name == "id"
    bad = tmp_path / "bad.yaml"
    bad.write_text("openapi: '1.0'\npaths: {}")
    with pytest.raises(ValueError):
        parse_openapi_file(bad, repo_id="repo:test", snapshot_id="snap:test")


async def test_plugin_reload_resources_and_http_trace(tmp_path: Path) -> None:
    repo = tmp_path / "repo"
    repo.mkdir()
    _write_http_repo(repo)
    server = MCPServer(McpServerConfig(workspace_path=tmp_path / "workspace"))
    await server.initialize()
    try:
        build_task = await server.call_tool("graph_build", {"repo_path": str(repo)})
        task_id = build_task.payload["task"]["task_id"]
        for _ in range(100):
            status = await server.call_tool("task_status", {"task_id": task_id})
            if status.payload["task"]["status"] == "completed":
                break
            await asyncio.sleep(0.01)
        repo_id = status.payload["task"]["result"]["repo_id"]
        reload_result = await server.call_tool(
            "plugin_reload", {"plugin_id": "http-rest", "repo_ids": [repo_id]}
        )
        assert reload_result.payload["interface_records_updated"] >= 1
        assert any(
            note["method"] == "notifications/resources/list_changed"
            for note in reload_result.notifications
        )
        listing = await server.read_resource("code-intelligence://interfaces")
        assert listing.payload["total_interface_records"] >= 1
        interface_name = quote("GET /users/{id}", safe="")
        record = await server.read_resource(
            f"code-intelligence://interfaces/http-rest/{interface_name}"
        )
        assert record.payload["operations"][0]["client_callsite_node_ids"]
        trace = await server.call_tool(
            "trace_cross_language",
            {
                "repo": repo_id,
                "symbol": "get_user",
                "plugins": ["http-rest"],
                "max_hops": 4,
            },
        )
        assert trace.payload["total_hops"] >= 2
        callers = await server.call_tool(
            "find_callers",
            {
                "repo": repo_id,
                "symbol": "get_user",
                "include_cross_language": True,
                "depth": 3,
            },
        )
        assert callers.payload["cross_language_hops"]

        graph_slice = await server.call_tool(
            "get_graph_slice",
            {"repo": repo_id, "files": ["server.py", "client.ts"]},
        )
        assert "nodes" in graph_slice.payload

        reload_task = await server.call_tool(
            "plugin_reload",
            {"plugin_id": "http-rest", "repo_ids": [repo_id], "task": True},
        )
        reload_task_id = reload_task.payload["task"]["task_id"]
        for _ in range(100):
            reload_status = await server.call_tool(
                "task_status", {"task_id": reload_task_id}
            )
            if reload_status.payload["task"]["status"] == "completed":
                break
            await asyncio.sleep(0.01)
        assert reload_status.payload["task"]["status"] == "completed"

        with pytest.raises(Exception, match="symbol could not be resolved"):
            await server.call_tool(
                "trace_cross_language",
                {"repo": repo_id, "symbol": "missing-symbol"},
            )
        with pytest.raises(Exception, match="plugin_id must be a string"):
            await server.call_tool("plugin_reload", {"plugin_id": 123})
    finally:
        await server.close()


async def test_websocket_and_idl_plugins_index_and_link(tmp_path: Path) -> None:
    repo = tmp_path / "repo"
    repo.mkdir()
    _write_websocket_repo(repo)
    _write_idl_repo(repo)
    workspace = await WorkspaceStore.initialize(tmp_path / "workspace", in_memory=True)
    try:
        build = await IndexingService(workspace).graph_build(repo)
        repo_record = await workspace.registry.get_repo(build.repo_id)
        snapshot = await workspace.snapshots.get_latest_snapshot(build.repo_id)
        assert snapshot is not None

        ws = WebSocketPlugin()
        detected = await ws.detect(repo_record, snapshot, repo_files(repo))
        indexed = await ws.index(repo_record, snapshot, detected, PluginConfig())
        linked = await ws.link(
            repo_record, snapshot, indexed, workspace, PluginConfig()
        )
        assert linked.nodes_emitted == 1
        assert linked.edges_emitted >= 1

        idl = OmniOrbIdlPlugin()
        detected_idl = await idl.detect(repo_record, snapshot, repo_files(repo))
        indexed_idl = await idl.index(
            repo_record, snapshot, detected_idl, PluginConfig()
        )
        assert indexed_idl.interface_records[0].operations[0].name == "add"
        assert indexed_idl.interface_records[0].generated_artifacts
        await idl.link(repo_record, snapshot, indexed_idl, workspace, PluginConfig())

        edges = await workspace.queries.fetch_edges_by_type(
            build.repo_id, GraphEdgeType.exposes.value
        )
        assert edges
    finally:
        await workspace.close()


async def test_reload_service_and_traversal_engine(tmp_path: Path) -> None:
    repo = tmp_path / "repo"
    repo.mkdir()
    _write_http_repo(repo)
    workspace = await WorkspaceStore.initialize(tmp_path / "workspace", in_memory=True)
    try:
        build = await IndexingService(workspace).graph_build(repo)
        registry = build_default_registry()
        payload = await reload_plugins(
            workspace,
            registry,
            plugin_id="http-rest",
            repo_ids=[build.repo_id],
        )
        assert payload["plugins_reloaded"] == ["http-rest"]
        records = await InterfaceRecordStore(workspace).list_records("http-rest")
        assert records
        handler = [
            node
            for node in await workspace.queries.fetch_nodes_by_type(
                build.repo_id, "function"
            )
            if node.label == "get_user"
        ][0]
        result = await CrossLanguageTraverser(registry, workspace).traverse(
            handler.node_id, max_hops=4, plugins=["http-rest"]
        )
        assert result.reached_node_ids
        high_cutoff = await CrossLanguageTraverser(registry, workspace).traverse(
            handler.node_id,
            max_hops=4,
            plugins=["http-rest"],
            min_confidence="parser",
        )
        assert high_cutoff.ambiguous_candidates
    finally:
        await workspace.close()
